Email feature
seansackowitz/associate-consultant-enablement-lab pull request #1
Opened 2017-03-01 21:18 UTC by homeski

2017-03-01 22:01 UTC, robojukie commented
![image](https://cloud.githubusercontent.com/assets/7130850/23483342/8bc7e5da-fea0-11e6-922f-b3c30199b870.png)

UI - buttons should stay inside the modal background

2017-03-01 22:03 UTC, robojukie requested changes

2017-03-01 22:03 UTC, robojukie commented on lab/lab-web/src/main/webapp/www/components/performances/add-modal/add.html
> +        <label>Email</label>
Email should probably sit under Performer Name, I think it's better UX

2017-03-01 22:21 UTC, homeski commented
fixed both comments

2017-03-02 19:32 UTC, robojukie commented
On venue add modal email would be better back under name, before city

2017-03-02 19:33 UTC, merged